<?php 
// Print-friendly report view. Expects $data set in session by ReportController::exportPDF
// Variables: expenses (array), summary (array), total_spent (number), month (int), year (int)
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vinimaya Report - <?php echo date('F Y', mktime(0,0,0,$data['month'],1,$data['year'])); ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none; }
        }
        body { padding: 24px; }
        h1, h2 { margin-bottom: 16px; }
        table { font-size: 14px; }
    </style>
<?php /* Simple guard: ensure expected keys exist */ ?>
<?php $expenses = $data['expenses'] ?? []; ?>
<?php $summary = $data['summary'] ?? []; ?>
<?php $total_spent = $data['total_spent'] ?? 0; ?>
</head>
<body>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h3 mb-0">Vinimaya Expense Report</h1>
        <button class="btn btn-primary no-print" onclick="window.print()">Print / Save as PDF</button>
    </div>

    <p class="text-muted">Period: <strong><?php echo date('F Y', mktime(0,0,0,$data['month'],1,$data['year'])); ?></strong></p>
    <p class="mb-4">Total Spent: <strong class="text-danger">₹<?php echo number_format((float)$total_spent, 2); ?></strong></p>

    <h2 class="h5">Category Summary</h2>
    <div class="table-responsive mb-4">
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <th>Category</th>
                    <th>Amount (₹)</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($summary as $row): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($row['category']); ?></td>
                        <td class="text-danger">₹<?php echo number_format((float)$row['total'], 2); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <h2 class="h5">Detailed Expenses</h2>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Amount (₹)</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($expenses as $exp): ?>
                    <tr>
                        <td><?php echo date('Y-m-d', strtotime($exp['expense_date'])); ?></td>
                        <td><?php echo htmlspecialchars($exp['category']); ?></td>
                        <td><?php echo htmlspecialchars($exp['description'] ?? ''); ?></td>
                        <td class="text-danger">₹<?php echo number_format((float)$exp['amount'], 2); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <p class="text-center text-muted mt-4">Generated by Vinimaya</p>
</body>
</html>


